# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /backend

# Install system dependencies (for example, to support certain Python packages)
# RUN apt-get update && apt-get install -y --no-install-recommends gcc libpq-dev

# Copy the requirements.txt file to the container
COPY requirements.txt /backend/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend application code into the container
COPY . /backend/

# Expose the port your FastAPI backend will run on
EXPOSE 8000

# Command to run FastAPI using uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
